<!DOCTYPE html>
<html lang="fr-FR">
<head>
	<meta charset="utf-8">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta property="og:locale" content="fr_FR">
	<meta property="og:type" content="blog">
	<meta property="og:site_name" content="template blog">
	<meta property="og:title" content="Blog Template - Connexion">
	<meta property="og:url" content="https://mickaelsorhaindo.fr/">
	<script async="" src="//www.google-analytics.com/analytics.js"></script>
	<meta name="viewport" content="initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Blog Template - Connexion</title>
		<meta name="description" content="Après inscription, vous pouvez vous connecter et accéder à votre profil, et diverses autres option." />
	<!-- FONTAWESOME -->

	<!-- STYLE CSS -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="../public/css/style.css">
</head>
<body>
	<!-- HEADER -->
	<?php 
	require_once '../public/includes/header.php'; 
	require_once '../public/includes/title.php'; 
	?>

	<?php if ( !empty($_SESSION) && $_SESSION['connected'] ) {
			connectTitle('Connexion');
		} else {
			addTitle('Connexion');
		} 
		?>
		
	<section>
			<!-- Formulaire de connexion -->
			<div class="container">

				<div class="formulaire">
					<form action="" method="POST">

						<div class="form-group flex column center">
							<label for="username">Username/ Mail</label>
							<input type="text" name="login" class="form-control">
						</div>

						<div class="form-group flex column center">
							<label for="password">Password</label>
							<input type="password" name="password" class="form-control">
						</div>

						<div class="form-group flex center">
							<input type="submit" value="SE CONNECTER" class="form-control validate">	
						</div>
					</form>
				</div>
			</div>
		</section>
	<!-- FOOTER -->
	<?php require_once '../public/includes/footer.php'; ?>

	<script src="../public/libs/jquery-3.2.1.min.js"></script>
	<script src="../public/js/main.js"></script>
</body>
</html>