<!DOCTYPE html>
<html lang="fr-FR">
<head>
	<meta charset="utf-8">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta property="og:locale" content="fr_FR">
	<meta property="og:type" content="blog">
	<meta property="og:site_name" content="template blog">
	<meta property="og:title" content="Blog Template - Espace Membres">
	<meta property="og:url" content="https://mickaelsorhaindo.fr/">
	<script async="" src="//www.google-analytics.com/analytics.js"></script>
	<meta name="viewport" content="initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Blog Template - Espace Membres</title>
	<meta name="description" content="Espace Membre accessible par l'administrateur uniquement. " />

	<!-- STYLE CSS -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="../public/css/style.css">
</head>
<body>
	<?php 
		require_once '../public/includes/header.php'; 
		require_once '../public/includes/title.php';
		?>

	<?php if( !empty($_SESSION) && $_SESSION['connected'] && $_SESSION['statut'] === 'admin'): ?>
	<main>
		<?php 
		if ( !empty($_SESSION) && $_SESSION['connected'] ) {
			echo connectTitle('Espace Membres');
		} else {
			echo addTitle('Espace Membres');
		} 
		?>
		<section class="container">
				<ul class="table">
						<li class="flex row space-between">
							<div class="thead">ID</div>
							<div class="thead">Username</div>
							<div class="thead">Date d'inscription</div>
							<div class="thead none-mobile">Statut</div>
						</li>
					<?php foreach($users as $user): ?>
						<li class="flex row space-between">
							<div class="tbody"> <a href="user_profil.php?userID=<?= $user['id'] ?>"><?= $user['id']; ?></a> </div>
							<div class="tbody"> <?= $user['username']; ?> </div>
							<div class="tbody"> <?= $user['date_inscription']; ?> </div>
							<?php if(!empty($user['statut'])): ?>
							<div class="tbody none-mobile"> <?= $user['statut']; ?> </div>
							<?php else : ?>
							<div class="tbody"> None </div>
							<?php endif; ?>
						</li>
					<?php endforeach; ?>
				</ul>
		</section>
	</main>

	<?php else: ?>
	
	<main>
		<section class="slide">
			<div class="container">
				<h1 class="orange"> Vous n'avez pas les autorisations pour visiter cette page!! </h1>
			</div>
		</section>
	</main>	
<?php endif; ?>

	<?php require_once '../public/includes/footer.php'; ?>

	<script src="../public/libs/jquery-3.2.1.min.js"></script>
	<script src="../public/js/main.js"></script>
</body>
</html>