

<!DOCTYPE html>
<html lang="fr-FR">
<head>
	<meta charset="utf-8">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta property="og:locale" content="fr_FR">
	<meta property="og:type" content="blog">
	<meta property="og:site_name" content="template blog">
	<meta property="og:title" content="Blog Template - Profil">
	<meta property="og:url" content="https://mickaelsorhaindo.fr/">
	<script async="" src="//www.google-analytics.com/analytics.js"></script>
	<meta name="viewport" content="initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Blog Template - Mon Profil</title>
	<meta name="description" content="Sur cette page, vous pourrez personnaliser vos informations et votre avatar. " />
	
	<!-- STYLE CSS -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="../public/css/style.css">
</head>
<body>
	<?php 
		require_once '../public/includes/header.php'; 
		require_once '../public/includes/title.php';
		?>

	<main>
		<?php if ( !empty($_SESSION) && $_SESSION['connected'] ) {
			echo connectTitle('Mon Profil');
		} else {
			echo addTitle('Mon Profil');
		} 
		?>
	<section class="container">
		<div>
			<h1 class="nom_profil orange"><?= $_SESSION['username'] ?></h1>
			<hr class="hr">
		</div>
	</section>
	<section class="container">
		
		<div class="formulaire">
			<form action="profil_update.php" method="POST" enctype="multipart/form-data" class="profil_avatar">

				<div class="form-group flex column center">
					<div class="avatar_empty" <?php if(!empty($user['avatar'])): ?> style=" background-image: url( ../public/membres/avatars/<?= $user['avatar'] ?> ); background-size: cover;" <?php endif; ?> >
					</div>
					<label for="avatar">Modifier mon avatar</label>
					<input type="file" name="avatar" class="form-control">
				</div>
				<div class="form-group flex column center">
					<input type="submit" class="form-control validate" value="MODIFIER">
				</div>
			</form>
			<?php if(isset($msg)) { echo $msg; } ?>
		</div>
	</section>
	<section class="container">
		<div class="formulaire">
					<form action="profil_update.php" method="POST">
						<div class="form-group flex column center">
							<label for="username">Change my Username</label>
							<input type="text" name="username" value="<?= $_SESSION['username']; ?>" class="form-control">
						</div>

						<div class="form-group flex column center">						
							<label for="mail">Modify my address mail</label>
							<input type="email" name="mail" value="<?= $_SESSION['mail'] ?>" class="form-control">
						</div>
						<?php if( isset($_POST) && !empty($_POST['mail']) && !filter_var($_POST['mail']) ){
							echo "<script>alert(\"Veuillez entrer une adresse valide!\")</script>";
						} ?>
						<div class="form-group flex column center">
							<label for="password">My new password</label>
							<input type="password" name="password" class="form-control" >
						</div>
						<div class="form-group flex column center">
							<label for="password_verif">Confirm new password</label>
							<input type="password" name="password_verif" class="form-control">
						</div>
						<?php if( isset($_POST) && !empty($_POST['password'])&& !empty($_POST['password_verif']) && $_POST['password'] !== $_POST['password_verif'] ){
							echo "<script>alert(\"Veuillez retaper le même mot de passe!\")</script>";
						} ?>
						<div class="form-group flex column center">
							<input type="submit" value="ENREGISTRER" class="form-control validate">
						</div>
					</form>
				</div>
	</section>

	</main>

	<?php require_once '../public/includes/footer.php'; ?>

	<script src="../public/libs/jquery-3.2.1.min.js"></script>
	<script src="../public/js/main.js"></script>
</body>
</html>