<!DOCTYPE html>
<html lang="fr-FR">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Blog Template - Mise à Jour</title>
	<!-- FONTAWESOME -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	<!-- STYLE CSS -->
	<link rel="stylesheet" type="text/css" href="../public/css/style.css">
</head>
<body>
	<?php require_once '../public/includes/header.php'; ?>
	<main>
		<section class="container">
			<p> Le profil a été mis à jour... Vous allez être redirigé vers votre espace dans <span id="countdown">5</span> seconde(s) </p>
		</section>
	</main>
	<?php require_once '../public/includes/footer.php'; ?>
	<script src="../public/js/main.js"></script>
</body>
</html>